import fs from "node:fs";

const args = process.argv.slice(2);
let antomFile = "/Users/david/codot-secrets/antom.env";
let outFile = ".env.local";

for (let index = 0; index < args.length; index += 1) {
  if (args[index] === "--antom-file") {
    antomFile = args[index + 1];
    index += 1;
  } else if (args[index] === "--out") {
    outFile = args[index + 1];
    index += 1;
  }
}

function parseEnvFile(file) {
  if (!file || !fs.existsSync(file)) return {};
  const result = {};
  const lines = fs.readFileSync(file, "utf8").split(/\r?\n/);
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const equals = trimmed.indexOf("=");
    if (equals < 0) continue;
    const key = trimmed.slice(0, equals).trim();
    let value = trimmed.slice(equals + 1).trim();
    value = value.replace(/^['"]|['"]$/g, "");
    result[key] = value;
  }
  return result;
}

function normalizePem(value) {
  return String(value || "").replace(/\\n/g, "\n").trim();
}

function wrapPemBody(value, label) {
  const normalized = normalizePem(value);
  const compact = normalized
    .replace(/-----BEGIN [^-]+-----/g, "")
    .replace(/-----END [^-]+-----/g, "")
    .replace(/\s+/g, "");
  const lines = compact.match(/.{1,64}/g)?.join("\n") || compact;
  return `-----BEGIN ${label}-----\n${lines}\n-----END ${label}-----`;
}

function escapedEnvValue(value) {
  return String(value || "").replace(/\n/g, "\\n");
}

const existing = parseEnvFile(outFile);
const antom = parseEnvFile(antomFile);
const next = {
  NEXT_PUBLIC_SITE_URL: existing.NEXT_PUBLIC_SITE_URL || "https://silverroc.com",
  NEXT_PUBLIC_SUPABASE_URL: existing.NEXT_PUBLIC_SUPABASE_URL || "",
  NEXT_PUBLIC_SUPABASE_ANON_KEY: existing.NEXT_PUBLIC_SUPABASE_ANON_KEY || "",
  SUPABASE_SERVICE_ROLE_KEY: existing.SUPABASE_SERVICE_ROLE_KEY || "",
  ANTOM_ENV: existing.ANTOM_ENV || antom.ANTOM_ENV || "sandbox",
  ANTOM_GATEWAY_URL: existing.ANTOM_GATEWAY_URL || antom.ANTOM_GATEWAY_URL || "",
  ANTOM_CLIENT_ID: existing.ANTOM_CLIENT_ID || antom.ANTOM_CLIENT_ID || "",
  ANTOM_MERCHANT_ID: existing.ANTOM_MERCHANT_ID || antom.ANTOM_MERCHANT_ID || "",
  ANTOM_PRIVATE_KEY: existing.ANTOM_PRIVATE_KEY || "",
  ANTOM_PUBLIC_KEY: existing.ANTOM_PUBLIC_KEY || antom.ANTOM_PUBLIC_KEY || "",
  ANTOM_DEFAULT_CURRENCY: existing.ANTOM_DEFAULT_CURRENCY || "CNY",
  ANTOM_MONTHLY_PRICE_MINOR: existing.ANTOM_MONTHLY_PRICE_MINOR || "990",
  ANTOM_PAYMENT_METHODS: existing.ANTOM_PAYMENT_METHODS || antom.ANTOM_PAYMENT_METHODS || "ALIPAY",
  ANTOM_ENABLE_SIMULATE: existing.ANTOM_ENABLE_SIMULATE || "false"
};

if (!next.ANTOM_PRIVATE_KEY && antom.ANTOM_PRIVATE_KEY_FILE && fs.existsSync(antom.ANTOM_PRIVATE_KEY_FILE)) {
  next.ANTOM_PRIVATE_KEY = escapedEnvValue(wrapPemBody(fs.readFileSync(antom.ANTOM_PRIVATE_KEY_FILE, "utf8"), "PRIVATE KEY"));
}

const content = [
  "# Generated by scripts/prepare-env.mjs. Do not commit.",
  ...Object.entries(next).map(([key, value]) => `${key}=${value}`)
].join("\n") + "\n";

fs.writeFileSync(outFile, content, { mode: 0o600 });

const missing = Object.entries(next)
  .filter(([key, value]) => !value && key !== "ANTOM_MERCHANT_ID")
  .map(([key]) => key);

console.log(`Wrote ${outFile}`);
if (missing.length) {
  console.log("Still missing:");
  for (const key of missing) console.log(`- ${key}`);
}
